export enum ClientEvent {
  ERROR = "ERROR",
  JOINED = "JOINED",
  LEFT = "LEFT",
  KICKED = "KICKED",
  LOBBY_LIST = "LOBBY_LIST",
  CREATE_LOBBY = "CREATE_LOBBY",
  UPDATE_LOBBY = "UPDATE_LOBBY",
  DELETE_LOBBY = "DELETE_LOBBY",
  TRANSFER_OWNER = "TRANSFER_OWNER",
  GAME_CREATED = "GAME_CREATED",
  GAME_RESULT = "GAME_RESULT",
  TOURNAMENT_WON = "TOURNAMENT_WON",
  WAITING_OPPONENTS = "WAITING_OPPONENTS",
}

export enum ServerEvent {
  CREATE = "CREATE",
  ACTION = "ACTION",
}

export enum Action {
  JOIN = "JOIN",
  LEAVE = "LEAVE",
  LAUNCH = "LAUNCH",
  KICK = "KICK",
  SWITCH_READY = "SWITCH_READY",
}
